/*

 GAME_BKG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : L:\LOGICIELS\Devellopement\gameboy\TILE\gametile.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define game_bkgWidth 20
#define game_bkgHeight 19
#define game_bkgBank 0

extern const unsigned char game_bkg[];

/* End of GAME_BKG.H */
